-- MySQL Script generated by MySQL Workbench
-- Thu Jun  1 10:40:13 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pizzeria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pizzeria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pizzeria` DEFAULT CHARACTER SET utf8 ;
USE `pizzeria` ;

-- -----------------------------------------------------
-- Table `pizzeria`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`client` (
  `id_client` INT NOT NULL AUTO_INCREMENT,
  `client_nom` VARCHAR(45) NOT NULL,
  `client_cognom1` VARCHAR(45) NOT NULL,
  `client_cognom2` VARCHAR(45) NOT NULL,
  `client_telf` INT(9) NULL,
  PRIMARY KEY (`id_client`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`botiga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`botiga` (
  `id_botiga` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id_botiga`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`adreça`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`adreça` (
  `id_adreça` INT NOT NULL,
  `adreça_carrer` VARCHAR(45) NOT NULL,
  `adreça_num` INT(3) NOT NULL,
  `adreça_cp` INT(5) NOT NULL COMMENT 'Codi Postal',
  `adreça_localitat` VARCHAR(45) NOT NULL,
  `adreça_provicia` VARCHAR(45) NOT NULL,
  `botiga_id_botiga` INT NULL,
  `client_id_client` INT NULL,
  PRIMARY KEY (`id_adreça`),
  INDEX `fk_adreça_botiga1_idx` (`botiga_id_botiga` ASC) VISIBLE,
  INDEX `fk_adreça_client1_idx` (`client_id_client` ASC) VISIBLE,
  CONSTRAINT `fk_adreça_botiga1`
    FOREIGN KEY (`botiga_id_botiga`)
    REFERENCES `pizzeria`.`botiga` (`id_botiga`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_adreça_client1`
    FOREIGN KEY (`client_id_client`)
    REFERENCES `pizzeria`.`client` (`id_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`comanda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`comanda` (
  `id_comanda` INT NOT NULL AUTO_INCREMENT,
  `comanda_col` VARCHAR(45) NULL,
  `comanda_data/hora` DATETIME NULL,
  `comanda_tipus` VARCHAR(45) NULL,
  `comanda_pizzes` INT NULL,
  `comanda_hamburgueses` INT NULL,
  `comanda_begudes` INT NULL,
  `comanda_preu` DECIMAL(2) NOT NULL,
  `client_id_client` INT NOT NULL,
  `botiga_id_botiga` INT NOT NULL,
  PRIMARY KEY (`id_comanda`),
  INDEX `fk_comanda_client1_idx` (`client_id_client` ASC) VISIBLE,
  INDEX `fk_comanda_botiga1_idx` (`botiga_id_botiga` ASC) VISIBLE,
  CONSTRAINT `fk_comanda_client1`
    FOREIGN KEY (`client_id_client`)
    REFERENCES `pizzeria`.`client` (`id_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comanda_botiga1`
    FOREIGN KEY (`botiga_id_botiga`)
    REFERENCES `pizzeria`.`botiga` (`id_botiga`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`categoria` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `categoria_nom` VARCHAR(45) NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`producte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`producte` (
  `id_producte` INT NOT NULL AUTO_INCREMENT,
  `producte_nom` VARCHAR(45) NOT NULL,
  `producte_descripcio` VARCHAR(45) NOT NULL,
  `producte_img` BLOB NULL,
  `producte_preu` DECIMAL(2) NOT NULL,
  `categoria_id_categoria` INT NULL,
  PRIMARY KEY (`id_producte`),
  INDEX `fk_producte_categoria1_idx` (`categoria_id_categoria` ASC) VISIBLE,
  CONSTRAINT `fk_producte_categoria1`
    FOREIGN KEY (`categoria_id_categoria`)
    REFERENCES `pizzeria`.`categoria` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`empleat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`empleat` (
  `id_empleat` INT NOT NULL AUTO_INCREMENT,
  `empleat_nom` VARCHAR(45) NOT NULL,
  `empleat_cognom1` VARCHAR(45) NOT NULL,
  `empleat_cognom2` VARCHAR(45) NOT NULL,
  `empleat_nif` VARCHAR(10) NOT NULL,
  `empleat_telf` INT(9) NULL,
  `empleat_tipus` VARCHAR(45) NOT NULL,
  `botiga_id_botiga` INT NOT NULL,
  PRIMARY KEY (`id_empleat`),
  INDEX `fk_empleat_botiga1_idx` (`botiga_id_botiga` ASC) VISIBLE,
  CONSTRAINT `fk_empleat_botiga1`
    FOREIGN KEY (`botiga_id_botiga`)
    REFERENCES `pizzeria`.`botiga` (`id_botiga`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`repartiment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`repartiment` (
  `empleat_id_empleat` INT NOT NULL,
  `comanda_id_comanda` INT NOT NULL,
  `repartiment_data` DATETIME NOT NULL,
  PRIMARY KEY (`empleat_id_empleat`, `comanda_id_comanda`),
  INDEX `fk_repartiment_comanda1_idx` (`comanda_id_comanda` ASC) VISIBLE,
  CONSTRAINT `fk_repartiment_empleat1`
    FOREIGN KEY (`empleat_id_empleat`)
    REFERENCES `pizzeria`.`empleat` (`id_empleat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_repartiment_comanda1`
    FOREIGN KEY (`comanda_id_comanda`)
    REFERENCES `pizzeria`.`comanda` (`id_comanda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`detalles_comanda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`detalles_comanda` (
  `comanda_id_comanda` INT NOT NULL,
  `producte_id_producte` INT NOT NULL,
  `detalles_comanda_num_producto` INT NOT NULL,
  PRIMARY KEY (`comanda_id_comanda`, `producte_id_producte`),
  INDEX `fk_detalles_comanda_producte1_idx` (`producte_id_producte` ASC) VISIBLE,
  CONSTRAINT `fk_detalles_comanda_comanda1`
    FOREIGN KEY (`comanda_id_comanda`)
    REFERENCES `pizzeria`.`comanda` (`id_comanda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalles_comanda_producte1`
    FOREIGN KEY (`producte_id_producte`)
    REFERENCES `pizzeria`.`producte` (`id_producte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
